[package]
name = "bitcoin-spv"
version = "0.1.0"
authors = ["Tamas Blummer <tamas.blummer@gmail.com>"]
license = "Apache-2.0"
homepage = "https://github.com/rust-bitcoin/rust-bitcoin-spv/"
repository = "https://github.com/rust-bitcoin/rust-bitcoin-spv/"
documentation = "https://github.com/rust-bitcoin/rust-bitcoin-spv/"
description = "SPV client for Bitcoin"
keywords = [ "bitcoin", "SPV" ]
readme = "README.md"

[lib]
name = "bitcoin_spv"
path = "src/lib.rs"

[[bin]]
name = "bitcoin_spv"
path = "src/bin/main.rs"

[dependencies]
bitcoin = { version = "0.15", features = ["bitcoinconsensus"] }
hammersbald = { path="../hammersbald", features=["bitcoin_support"]}
lightning = "0.0.7"
mio = "0.6"
rand = "0.5"
siphasher = "0.2"
log = "0.4"
simple_logger = "0.5.0"
rusqlite = { version = "0.13.0", features = ["bundled"] }
byteorder = "1.2"
futures={ git= "https://github.com/tamasblummer/futures-rs.git", tag = "0.2.1" }
futures-timer= { git= "https://github.com/tamasblummer/futures-timer.git", branch = "futures_0.2.1" }

[dev-dependencies]
rustc-serialize = "0.3"
hex = "0.3"
tempfile = "3.0.2"
